### ISSUE TITLE
v1.3: PHPStan fails in Travis

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/PluginSkeleton#149]
Haven't modified anything in the Travis / PHPStan configs, PluginSkeleton v1.3.5:

```
$ vendor/bin/phpstan analyse -c phpstan.neon -l max src/
In XmlServiceMapFactory.php line 25:
                                                                               
  Container tests/Application/var/cache/test/ApplicationTestDebugProjectConta  
  iner.xml not exists                                                          
                                                                               
analyse [-c|--configuration CONFIGURATION] [-l|--level LEVEL] [--no-progress] [--debug] [-a|--autoload-file AUTOLOAD-FILE] [--error-format ERROR-FORMAT] [--errorFormat ERRORFORMAT] [--memory-limit MEMORY-LIMIT] [--] [<paths>]...
The command "vendor/bin/phpstan analyse -c phpstan.neon -l max src/" exited with 1.
```

**Comment by stefandoorn** [comment]
Same issue happens here: https://travis-ci.org/Sylius/PluginSkeleton/jobs/463241133

**Comment by stefandoorn** [comment]
I have to use this path in my most recent plugin: 

```        
container_xml_path: tests/Application/var/cache/test/ApplicationTests_StefanDoorn_SyliusSeoUrlPlugin_Application_KernelTestDebugContainer.xml
```

**Comment by mmenozzi** [comment]
Here is the same. Setting the proper `container_xml_path` in the `phpstan.neon` does the job, thank you @stefandoorn!

Anyway I'm not sure how we should fix it at plugin skeleton level. The problem is that the new name is different for every plugin so if we change the `phpstan.neon` here in the skeleton then we have to add some documentation in the `README.md` to say that that configuration must be adjusted when the plugin name changes.

Maybe @pamil and/or @Zales0123 have some thoughts about this.
