### ISSUE TITLE
How to test for Sylius 1.1 + 1.2 + 1.3 & PHP 7.1 + 7.2 & Symfony 3.4 + 4.1/4.2

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/PluginSkeleton#151]
I just started developing a new plugin. In case I would like my plugin to support Sylius v1.1 and the underlying, how am I going to do this in Travis? I could go with v1.3 on the master, and create 'old' CI branches for v1.2 and v1.1, but that feels tedious to me. Also #130 & #104 pop up then. Only supporting ^1.3 feels also 'weird' to me, as the plugin itself should be able to support ^1.1. It's mainly that CI is hard on it..

Thanks!

**Comment by 4c0n** [comment]
Although I am not a big fan of git submodules, so far it works for testing on multiple Sylius versions. I haven't gone through the extent of adding multiple Symfony versions and PHP versions, but that's not the hard part and has been done many times over.

https://github.com/4c0n/SyliusBarcodeSearchPlugin/blob/master/.travis.yml

Another option, at least for public repos, is to use flex to literally install the plugin in a new Sylius standard installation and then somehow run the tests. As this works for public repos only I haven't bothered, because I have to maintain plugins in private repos as well and don't like doing things differently there.

Hopes this helps getting this very old topic of the ground!

**Comment by pamil** [comment]
Is it possible to add some custom config to that submodule?

**Comment by pamil** [comment]
Btw. let's move the discussion to #104 to keep it in one place.
